import { z } from 'zod';

const color = z.string().regex(/^#[0-9a-fA-F]{6}$/, 'Expected #rrggbb');

const httpUrl = z
  .string()
  .max(2048)
  .refine((v) => {
    try {
      const u = new URL(v);
      return u.protocol === 'http:' || u.protocol === 'https:';
    } catch {
      return false;
    }
  }, 'Only http(s) URLs are allowed');

// Uploaded asset paths are always generated by the server.
const uploadPath = z.string().regex(/^\/uploads\/[a-f0-9]{32}\.(png|jpg|webp|svg)$/);

export const IconSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('lucide'), value: z.string().regex(/^[a-z0-9-]{1,64}$/) }),
  z.object({ type: z.literal('upload'), value: uploadPath }),
]);

export const TileSchema = z.object({
  id: z.string().regex(/^[A-Za-z0-9_-]{1,40}$/),
  title: z.string().min(1).max(80),
  description: z.string().max(200).default(''),
  url: httpUrl,
  icon: IconSchema,
  colors: z
    .object({ bar1: color.optional(), bar2: color.optional(), bar3: color.optional(), fill: color.optional() })
    .optional(),
  openMode: z.enum(['auto', 'iframe', 'newTab']).default('auto'),
  embeddable: z.boolean().optional(),
});

export const GroupSchema = z.object({
  id: z.string().regex(/^[A-Za-z0-9_-]{1,40}$/),
  name: z.string().max(80),
  tiles: z.array(TileSchema).max(200),
});

export const ThemeSchema = z.object({
  bg: color,
  surface: color,
  text: color,
  accent: color,
  barColors: z.tuple([color, color, color]),
});

export const ConfigSchema = z.object({
  site: z.object({
    title: z.string().min(1).max(80),
    logoUrl: uploadPath.optional(),
    theme: ThemeSchema,
    mode: z.enum(['dark', 'light', 'auto']).default('auto'),
    columns: z.number().int().min(1).max(4).default(3),
  }),
  groups: z.array(GroupSchema).max(50),
});

export type Icon = z.infer<typeof IconSchema>;
export type Tile = z.infer<typeof TileSchema>;
export type Group = z.infer<typeof GroupSchema>;
export type Theme = z.infer<typeof ThemeSchema>;
export type Config = z.infer<typeof ConfigSchema>;

export const DEFAULT_CONFIG: Config = {
  site: {
    title: 'Tenax Navigation',
    theme: {
      bg: '#0e1020',
      surface: '#171a33',
      text: '#eef0ff',
      accent: '#f5a623',
      barColors: ['#f5a623', '#5b6cff', '#1f2250'],
    },
    mode: 'auto',
    columns: 3,
  },
  groups: [
    {
      id: 'tools',
      name: 'Tools',
      tiles: [
        {
          id: 'links',
          title: 'Links',
          description: 'Company link shortener',
          url: 'https://link.tenax.lv',
          icon: { type: 'lucide', value: 'link' },
          openMode: 'auto',
        },
        {
          id: 'wiki',
          title: 'Wiki',
          description: 'Internal documentation',
          url: 'https://en.wikipedia.org/wiki/Main_Page',
          icon: { type: 'lucide', value: 'book-open' },
          openMode: 'auto',
        },
        {
          id: 'github',
          title: 'GitHub',
          description: 'Source code (opens in new tab — blocks framing)',
          url: 'https://github.com',
          icon: { type: 'lucide', value: 'code' },
          openMode: 'newTab',
          embeddable: false,
        },
      ],
    },
  ],
};
